"""Added new column to Post model

Revision ID: 069f15284ae5
Revises: f72bd80c06e1
Create Date: 2023-12-22 16:46:43.322411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "069f15284ae5"
down_revision: Union[str, None] = "f72bd80c06e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("public", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "public")
    # ### end Alembic commands ###
