version: '3.8'

services:
  backend:
    image: backend
    build: .
    ports: 
      - 8000:8000
    environment:
      - ENV=${ENV}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITH=${ALGORITH}
      - ACCESS_TOKEN_EXPIRES_MINUTES=${ACCESS_TOKEN_EXPIRES_MINUTES}
      - PYTHONPATH=.
      - LOCAL_BD_CONNECTION_STRING={LOCAL_BD_CONNECTION_STRING}
    working_dir: /app
