#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '\nLint and typecheck frontend 🔎'
cd frontend
npm run lint:front
npm run stylelint
npm run check-types
echo '------------------'
echo '\n\nAudit frontend prod dependencies 🔦'
npm audit --omit=dev
# echo '\n------------------'
# echo '\n\nLint backend 🧹'
# npm run lint:back
# echo '\n------------------'
# echo '\n\nAudit backend 🧹'
# npm run audit:back
