#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Lint and typecheck frontend 🔎'
cd frontend
npm run lint:frontend
npm run stylelint
npm run check-types
echo '\nAudit prod dependencies 🔦'
npm audit --omit=dev
echo '\nLint backend 🧹'
npm run lint:backend

