name: Actio is action in latin

on:
  pull_request: 
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  test_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: npm i
      - name: Build the app
        run: npm run build
      - name: Create users
        run: npm run create-users
      - name: Run Cypress e2e
        run: npm run cypress:e2e
