name: Actio is action in Latin

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  test_frontend_job:
    runs-on: ubuntu-20.04
    env:
      working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
        working-directory: ${{env.working-directory}}
      - name: Build the app
        run: npm run build:test
        working-directory: ${{env.working-directory}}
      - name: Create users
        run: npm run create-users
        working-directory: ${{env.working-directory}}
      - name: Run Cypress e2e
        run: npm run cypress:e2e
        working-directory: ${{env.working-directory}}
  test_backend_job:
    runs-on: ubuntu-20.04
    env:
      working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      # manually create DB ...
      - name: Create DB
        run: |
          wget https://sqlite.org/2022/sqlite-autoconf-3380500.tar.gz
          tar -xvf sqlite-autoconf-3380500.tar.gz
          ./configure
          make
          sudo make install
        working-directory: ${{env.working-directory}}
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ${{env.working-directory}}
      - name: Create DB
        run: python -c 'from tests import create_db;create_db.create()'
        working-directory: ${{env.working-directory}}
      - name: Run tests
        run: ENV=test PYTHONPATH=. pytest -v
        working-directory: ${{env.working-directory}}
